var GAME_LEVELS = [
 ["     n                           ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                 ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                 @             o  ",   
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                o o                                                                ",
   "                        es            xxxx                                         ",
   "         xxxxx       xxxxx                       o                                 ",
   "                             f                              o                      ",
   "                 b        xxxxxx              xxxxxx                               ",
   "  xxxxx        x!!!x         d                          xxes    x                  ",
   "               x!!!x                                     xxxxxxxx                  ",
   "               xxxxx                                                               ",
   "         xxxxx                             xxxxx   xxxxx         o       o         ",
   "                                           x d x!!!x                               ",
   "                         o          fff    x   x!!!x         xes           x       ",
   "                                   xxxxxxxxx   xxxxx         xxxxxxxxxxxxxxx       ",
   "     xxxx                                                 xxxx                     ",
   " @   xxxx                        f                               o                 ",   
   "xxxxxxxxxxx                     xxxx                                          b xxx",
   "xxxxxxxxxxx    o            xxxxxxxx         xxx       x    xx       xxxxxxxx!!!xxx",
   "xxxxxxxxxxx         xxxxx   xxxxxxxx   x            o  x!!!!xxE      xxxxxxxx!!!xxx",
   "xxxxxxxxxxxE        xxxxx!!!xxxxxxxx!!!x               x!!!!xxxxxxxxxxxxxxxxx!!!xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxE       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                        x                                                                                         ",
   "                        x                                                                                         ",
   "                        x                                                                                        ", 
   "                      @ x                                         o                                              ",
   "               xxxxxxxxxx                                                                                        ",
   "                                          xxxxxxx                                                                ",
   "                            o                   xes            x                                                 ",
   "                                                xxxxxxxxxxxxxxxx!!!xxxxx                               o         ", 
   " xxxx                               b                          x!!!x                                             ",
   "                  xxxxxx         xxxxxxx        o              xxxxx          o                                  ",
   "                  x    x         x  d  x                                  f                           xxxx       ",
   "                  x    x   E   xxx     xxxxxxx                           xxxxxxxx!!!!!!x                         ",
   "es            xxxxx o  xxxxxxxxx             x   E  x                           x!!!!!!x                         ",
   "xxxxxx                                       xxxxxxxx                           x!!!!!!x                         ",
   "     x                                                                          xxxxxxxx                         ",
   "     x                                                             qe               d                            ",
   "     x!!!!!x      xxxxxx                                     xxxxxxxx                      x  E  xxxx            ",
   "     x!!!!!x           xf                                                                  xxxxxxx               ",
   "     x!!!!!x           xxxxxx                  o                                                        xxxxxxxx ",
   "     x!!!!!x                 xxxxxx!!!x                                                                          ",
   "     xxxxxxx                      x!!!x                                   xxxxx        o                         ",
   "                                  x!!!xxxxxxx                             xxxxx                                  ",
   "       o                          xxxxx     xxxxx       xxxx              xxxxx                    xxxxxx        ",
   "               xx                                                   xxxxxxxxxxxx      f            xxxxxx        ",
   "                                                                    xxxxxxxxxxxx    xxxxxx       xxxxxxxxxxxxxxxx",
   "     xxxx                                                o   xxxx   xxxxxxxxxxxx    xxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                                                             x  x!!!xxxxxxxxxxxxffffxxxxxx!!!!xxxxxxxxxxxxxxxxxxx",
   "  b                         es                               x  x!!!xxxxxxxxxxxx!!!!xxxxxx!!!!xxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!xxxxxxxxxxxxxfffffxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
                                                                                                                      
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                      @                                                                                  ",
   "                      x                                                                                  ",
   "                     xxx                                                                                 ",
   "                      x                                                                                  ",
   "                    xxxxx                                          o                                     ",
   "                      xes                                  xxxxx                       o                 ",
   "                   xxxxxxx                                 x   x                                         ",
   "             o        x                                xxxxx   x                                         ",
   "                      x                                x       xxxxxxx             xxxx                  ",
   "      xxxxx       xxxxxxxxx                       xxxxxxff                         x!!x                  ",
   "      x   x       x                            xxxxxxxxxxxxx                       x!!x                  ",
   "      x   x   E   x                            xd          x                      xxxxxx                 ",
   "      x   xxxxxxxxx          xxxxxx            x       o   x                       x  xfff               ",
   "      x                                        x         ffx                    xxxxxxxxxxxxx            ",
   "      xffffffff         o                      x      xxxxxx         o          x           x            ",
   "      xxxxxxxxx                          xxxx                                xxxxfffffx     x            ",
   "              x                                                              x  xxxxxxx  o  xxxxxx       ",
   "              x        xxxxxx        xx                               xxxxxxxx                        xx ",
   "              x             x        xx                                                                  ",
   "xxxxx         x             x   E    xx                          xx                xxx          xxxxxx   ",
   "  d x                       xxxxxxxxxxx               xxxxx!!!!!!x                        xx             ",
   "    xes                               xff             x   x!!!!!!x                      o  x             ",
   "    xxxxxxxxxxxxx                     xxxxxxxxxx!!!xxxx   x!!!!!!x      xxx                x             ",
   "                                               x!!!x      xxxxxxxx             x      E    x             ",
   "  o                        qe                  xxxxx                           xxxxxxxxxxxxx             ",
   "                      xxxxxxx                                                  x                         ",
   "   	xxxxxxxxx                                            o              xxxxxxxx     o          xxxxxxxxx",
   "   	x!!!!!!!x                                                   xx             x                x        ",
   "xxxxx!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx            xx             xxxxxxxxxxxxxxxxxx        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!x   xxxx     xxxxxx                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!x b x!!x     x!!!!x                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!xxxxx!!x  E  x!!!!xxxxx   xxxxxx       xxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  
  ["     z                             ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                 @           o     ",   
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   
   ["   p                              ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                 @            o    ",   
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
